### ISSUE TITLE
Docs: Create an issue template to add users as contributors 

### ISSUE THREAD

**Issue by adiati98** [open-sauced/guestbook#206]
## Description

To get our "Intro to Open Source" course participants into the flow of contributing to open source, we want them to learn  and experience creating an issue and link their PR to it later on.

Originally, we will let contributors to create an issue from scratch. However, adding an issue template would be a good practice for them to learn about issue's structure.

**Based on these discussions**:
- _Originally posted by @adiati98 in https://github.com/open-sauced/guestbook/issues/203#issuecomment-1875519001_
- _Originally posted by @BekahHW in https://github.com/open-sauced/guestbook/issues/203#issuecomment-1875991234_

## Suggested Solution

To make it easier for contributors and maintainers to triage, let's create a simple issue template with below sections and add instructions (coment them out) to each section:

- [x] 1. Create an `ISSUE_TEMPLATE` folder inside `.github` folder.
- [x] 2. Create a file call `feature_request.yml`.
- [x] 3. Add these to the template (*See our [Feature Request template](https://github.com/open-sauced/.github/blob/main/.github/ISSUE_TEMPLATE/feature_request.yml?plain=1) to help you out*):
    - [ ] name: 🚀 Feature request
    - [ ] description: Add contributors to the guest book 💡 
    - [ ] title: "Feature: "
    - [ ] labels: [💡 feature]
    - [ ] All have `validations: required: true`

    Atrributes' label in the body:
    - [ ] Description 
           ***description**: Please describe the issue — for example, "As part of the Intro to Open Source course, we are encouraged to contribute to this repo."*
    - [ ] Suggested solution
          ***description**: Suggest a solution — for example, "Add myself as a contributor."*
    - [ ] Code of Conduct agreement
    - [ ] Getting Started Instructions agreement

        ```yml
        type: checkboxes
        id: contribution
        attributes:
          label: Getting Started Instructions
          description: Please read [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) to add yourself as a contributor.
          options:
            - label: I agree to follow this project's Getting Started instructions.
              required: true
        ```
